### PR TITLE
Fixes random reboot,thanks:@Snuzzo

### PR DESCRIPTION
**Pull request by shaheerkv**
Changed the PANIC_TIMEOUT to 0

### CODE REVIEW

**Comment by marduk191** [comment]
If we use this patch, you would delete

```
 #ifndef CONFIG_PANIC_TIMEOUT
#define CONFIG_PANIC_TIMEOUT 0
#endif
```

from panic.c.

I think a better solution would be to just not define the timeout if this ends up testing properly.

**Comment by shaheerkv** [comment]
ok

**Comment by marduk191** [comment]
looks good, will test

**Comment by marduk191** [comment]
seems to help. I'd say it's ok. Wait for everyone to see it before you merge.

**Comment by mifl** [comment]
Please close the pull and add a new Pull Request with only one commit.

Something like this: "presto: defconfig: panic_timeout set to default"

If you need to add more text you can use the extended description.

Thanks.

**Pull request closed without merging**
