### PR TITLE
Snapdragon build optimization and enable interactive governor, various tweaks +crt animation fix feature

### PR DESCRIPTION
**Pull request by marduk191**

### CODE REVIEW

**Comment by mifl** [comment]
To complete the fix for crt off animation 

We can add in : arch/arm/mach-msm/cust_sky/Kconfig

```
config AVOID_COMPILE_ERRORS
    bool "Patch to avoid kernel compile errors"
    default y

+config PRESTO_CRT_OFF_ANIMATION
+   bool "Fix to crt off animation"
+   default y

config BUG_FIX_LCD_YUV_REVERSE
```

and in: kernel/power/fbearlysuspend.c

```
#ifdef CONFIG_PRESTO_CRT_OFF_ANIMATION
#include <linux/delay.h>
#endif

#ifdef CONFIG_PRESTO_CRT_OFF_ANIMATION
int fbearlysuspend_delay = 50;
#endif

#ifdef CONFIG_PRESTO_CRT_OFF_ANIMATION
/* FIXME: earlysuspend breaks androids CRT-off animation
* Sleep a little bit to get it played properly */

        msleep(fbearlysuspend_delay);
#endif
```

In this way the patch is set as a new feature.

**Comment by marduk191** [comment]
added a change for mifls proposal, check it for errors.

**Comment by marduk191** [comment]
ok this is the end of this pull. The next thing would be to remove plug from aio, but this isn't wise on the new kernel. Also 03 and linaro, neither of which add enough to justify maintaining another repo for prebuilts.

**Comment by jied83** [comment]
seems fine

**Comment by marduk191** [comment]
if nothing is broken I'll merge it tonight

**Pull request merged**
